### ISSUE TITLE
Error Running examples/windows.py on MacOS M1 under Wine - OpenGL.error.GLError: GLError(err = 1286)

### ISSUE THREAD

**Issue by alex-knyaz** [pyglfw/pyglfw#9]
### Issue Description:

I am trying to run the examples/windows.py script from the pyglfw repository under Wine on a MacOS M1 machine, but I am encountering an issue with OpenGL.error.GLError: GLError(err = 1286).

### Environment:

OS: MacOS M1
Python version: Python 3.11
Wine version: wine-8.10
glfw version: 2.6.2

### Steps to Reproduce:

Run the examples/windows.py script from the pyglfw repository under Wine on a MacOS M1 machine.

### Actual Result:

```
Traceback (most recent call last):
  File "Z:\Users\alex\Desktop\pyglfw\examples\windows.py", line 29, in <module>
    glClearColor(*colors[i])
  File "C:\users\alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in
 __call__
    return self( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1286,
        description = b'invalid framebuffer operation',
        baseOperation = glClearColor,
        cArguments = (0.0, 0.0, 1.0, 0.0)
)
```

### Expected Result:

The script runs successfully without raising a GLError.

### Additional Information:

The glfw3.dll is in the windows/system32 directory. _**Furthermore, non-pyglfw OpenGL apps, such as pygame, are working properly under the same Wine setup.**_

Please let me know if you need any further information to assist with debugging this issue. I am more than happy to provide whatever you might need to help resolve this.

**Comment by RomanValov** [comment]
Hey. Thank you for reporting the issue. Unfortunately I'm no longer actively maintaining the project and won't be able to invest time to investigate your issue. In case you'll end up with instructions/patches to solve it -- please share details on this thread.

Here some thoughts:
1) It looks like the issue is arisen at PyOpenGL code and have nothing to do with glfw/pyglfw. Otherwise you should got errors at pyglfw import statements.
2) As a method to prove that OpenGL is a reason -- try to comment out gl calls (glClearColor, glClear) and run the example.
3) All I can suggest is to update PyOpenGL version in your setup. But if it won't help probably PyOpenGL is not able to correctly determine your platform. So I would start digging this direction.

**Comment by alex-knyaz** [comment]
Thank you for the quick response. I will post the solution here if I find it.
